version: "3.8"
name: fastapi-crms-demo

services:
  crms:
    build:
      context: .
    ports:
      - "8000:80"
      - "5679:5679"
    depends_on:
      - db
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./app:/src/app
  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crms
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
  pgadmin-data:
