"""Added a column a_new_column

Revision ID: ead411cc0362
Revises: 72d543529fa8
Create Date: 2024-06-09 19:45:40.208655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead411cc0362'
down_revision: Union[str, None] = '72d543529fa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('a_new_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'a_new_column')
    # ### end Alembic commands ###
